# localhost: The WSL instance is running on the same
- hosts: localhost
  become: yes
  vars_files:
    - group_vars/vars.yml

  tasks:
  - name: Install poetry using pip
    pip:
      name: poetry
      state: present

