# localhost: The WSL instance is running on the same
- hosts: localhost
  become: yes
  vars_files:
    - group_vars/vars.yml

  tasks:
  - name: Create alias for microk8s.kubectl as kubectl
    become: true
    command: "snap alias microk8s.kubectl kubectl"
    