---
- name: Install chrony package
  package:
    name: chrony
    state: present

- name: Configure NTP servers
  lineinfile:
    path: /etc/chrony/chrony.conf
    line: "server <ntp_server>"
  vars:
    ntp_server: "your.ntp.server"

- name: Restart chrony service
  service:
    name: chrony
    state: restarted

- name: Update and upgrade packages 
  apt:
    update_cache: yes

- name: Add linuxadmin to sudoers
  lineinfile:
    path: /etc/sudoers
    line: 'linuxadmin ALL=(ALL) NOPASSWD:ALL'

- name: Install dependencies
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - snapd
    - curl


# You need to do wsl --shutdown to restart the WSL instance
- name: Activate systemd on wsl
  copy:
    dest: /etc/wsl.conf
    content: |
      [boot]
      systemd=true

- name: Install poetry using pip
  pip:
    name: poetry
    state: present

    
