---
- name: Update and upgrade packages 
  apt:
    update_cache: yes

- name: Add linuxadmin to sudoers
  lineinfile:
    path: /etc/sudoers
    line: 'linuxadmin ALL=(ALL) NOPASSWD:ALL'

- name: Install dependencies
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - snapd


# You need to do wsl --shutdown to restart the WSL instance
- name: Activate systemd on wsl
  copy:
    dest: /etc/wsl.conf
    content: |
      [boot]
      systemd=true

- name: Install Poetry
  shell: "curl -sSL https://install.python-poetry.org | python3 -"